In [1]:
import SimpleITK as sitk
import ants 
import os
import numpy as np
import glob

In [5]:
# 数据存储的路径
img_path = r"D:/Transmorph_Frame/Data/seg_need_nii/raw_images/new_nii_resampled_normalized_files/new_nii_resampled_normalized_cropped_files/"
point_path = r"D:/Transmorph_Frame/Data/seg_need_nii/raw_tumors_seg/new_nii_resampled_normalized_cropped_files/"
file_names = os.listdir(img_path)
CT_imgs = glob.glob(img_path + '*CT*.nii.gz')
MR_imgs = glob.glob(img_path + '*MR*cropped.nii.gz')
CT_points = glob.glob(point_path + '*CT*.nii.gz')
MR_points = glob.glob(point_path + '*MR*cropped.nii.gz')

In [7]:
test_zipped_imgs = zip(CT_imgs, MR_imgs, CT_points, MR_points)
# 图片读取
for fixed, moving, fixed_points, moving_points in test_zipped_imgs:
    f_img = ants.image_read(fixed)
    m_img = ants.image_read(moving)
    f_points = ants.image_read(fixed_points)
    m_points = ants.image_read(moving_points)
    # 图像配准
    mytx = ants.registration(fixed=f_img, moving=m_img, type_of_transform='Affine', reg_iterations=(160, 80, 40))
    warped_img = ants.apply_transforms(fixed=f_img, moving=m_img, transformlist=mytx['fwdtransforms'],
                                        interpolator='linear')
    warped_points = ants.apply_transforms(fixed=f_points, moving=m_points, transformlist=mytx['fwdtransforms'],
                                        interpolator='nearestNeighbor')
    ants.image_write(warped_img, moving.replace('.nii.gz', '_warped.nii.gz'))
    ants.image_write(warped_points, moving_points.replace('.nii.gz', '_warped.nii.gz'))
    print(np.unique(f_points.numpy()))
    print(np.unique(m_points.numpy()))
    print(np.unique(warped_points.numpy()))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 8. 9.]
[0. 1. 2. 3. 4. 5. 8. 9.]
[0. 1. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 4. 5. 6. 7. 8. 9.]
[0. 1. 4. 5. 6. 7. 8. 9.]
[0. 1. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 4. 5. 7. 8. 9.]
[0. 1. 2. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 5. 7.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[0. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 7. 8. 9.]
[0. 1. 2. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7

In [2]:
img_path = r"D:/Transmorph_Frame/Data/seg_need_nii/raw_images/new_nii_resampled_normalized_files/new_nii_resampled_normalized_cropped_files/"
point_path = r"D:/Transmorph_Frame/Data/seg_need_nii/raw_tumors_seg/new_nii_resampled_normalized_cropped_files/"
fixed_img = glob.glob(img_path + '*CT*.nii.gz')[0]
fixed_point = glob.glob(point_path + '*CT*.nii.gz')[0]
moving_imgs = glob.glob(img_path + '*cropped.nii.gz')[1:]
moving_points = glob.glob(point_path + '*cropped.nii.gz')[1:]

In [3]:
test_zipped_imgs = zip(moving_imgs, moving_points)
# 图片读取
for moving, moving_points in test_zipped_imgs:
    f_img = ants.image_read(fixed_img)
    m_img = ants.image_read(moving)
    f_points = ants.image_read(fixed_point)
    m_points = ants.image_read(moving_points)
    # 图像配准
    mytx = ants.registration(fixed=f_img, moving=m_img, type_of_transform='Affine', reg_iterations=(160, 80, 40))
    warped_img = ants.apply_transforms(fixed=f_img, moving=m_img, transformlist=mytx['fwdtransforms'],
                                        interpolator='linear')
    warped_points = ants.apply_transforms(fixed=f_points, moving=m_points, transformlist=mytx['fwdtransforms'],
                                        interpolator='nearestNeighbor')
    ants.image_write(warped_img, moving.replace('.nii.gz', '_warped.nii.gz'))
    ants.image_write(warped_points, moving_points.replace('.nii.gz', '_warped.nii.gz'))
    print(np.unique(f_points.numpy()))
    print(np.unique(m_points.numpy()))
    print(np.unique(warped_points.numpy()))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 8. 9.]
[0. 1. 2. 3. 4. 5. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 4. 5. 6. 7. 8. 9.]
[0. 1. 4. 5. 6. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 4. 5. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 4. 5. 6. 7. 8. 9.]
[0. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 4. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 3. 4. 5. 6. 7. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 2. 3. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 